<a href="https://colab.research.google.com/github/jejec0703/Machine-Learning-Deep-Learning/blob/master/Boston_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- linear regression
- ridge, lasso, elasticnet
- mse
- r2 score
- f1
- print

In [ ]:
from sklearn.datasets import load_boston

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

1. Linear Regression

In [ ]:
boston = load_boston()
X = boston.data
y = boston.target

In [ ]:
df_boston = pd.DataFrame(boston.data, columns=boston.feature_names)
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((404, 13), (404,), (102, 13), (102,))

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)
lin_reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = lin_reg.predict(X_train)
y_pred.shape

(404,)

In [ ]:
print('train score : {}'.format(lin_reg.score(X_train, y_train)))
print('test score : {}'.format(lin_reg.score(X_test, y_test)))

train score : 0.7508856358979672
test score : 0.6687594935356307


In [ ]:
lin_reg.coef_, lin_reg.intercept_

(array([-1.13055924e-01,  3.01104641e-02,  4.03807204e-02,  2.78443820e+00,
        -1.72026334e+01,  4.43883520e+00, -6.29636221e-03, -1.44786537e+00,
         2.62429736e-01, -1.06467863e-02, -9.15456240e-01,  1.23513347e-02,
        -5.08571424e-01]), 30.246750993923925)

In [ ]:
##### Unknown label type: 'continuous' : 연속형 데이터가 들어와서 에러남 
##### categorical 들어와야하는데

2. Ridge / Lasso / ElasticNet 

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
ridge = Ridge(alpha=0.001).fit(X_train, y_train)

In [ ]:
print('train score : {}'.format(ridge.score(X_train, y_train)))
print('test score : {}'.format(ridge.score(X_test, y_test)))

train score : 0.7508856291109945
test score : 0.6687586974995461


In [ ]:
ridge.coef_, ridge.intercept_

(array([-1.13048818e-01,  3.01142162e-02,  4.03215214e-02,  2.78407722e+00,
        -1.71888387e+01,  4.43891333e+00, -6.30727570e-03, -1.44766825e+00,
         2.62403820e-01, -1.06482208e-02, -9.15297505e-01,  1.23518659e-02,
        -5.08596323e-01]), 30.237220919203853)

In [ ]:
from sklearn.linear_model import Lasso

In [ ]:
lasso = Lasso(alpha=0.001).fit(X_train, y_train)

In [ ]:
print('train score : {}'.format(lasso.score(X_train, y_train)))
print('test score : {}'.format(lasso.score(X_test, y_test)))

train score : 0.7508814017164855
test score : 0.6687912341337345


In [ ]:
lasso.coef_, lasso.intercept_

(array([-1.12881360e-01,  3.01954998e-02,  3.89490293e-02,  2.76307020e+00,
        -1.68662604e+01,  4.43878387e+00, -6.51620597e-03, -1.44268060e+00,
         2.61824758e-01, -1.06817501e-02, -9.11693590e-01,  1.23646200e-02,
        -5.09377240e-01]), 30.02702982625408)

In [ ]:
from sklearn.linear_model import ElasticNet

In [ ]:
elastic = ElasticNet(alpha=0.001, l1_ratio=0.5).fit(X_train, y_train)

In [ ]:
print('train score : {}'.format(elastic.score(X_train, y_train)))
print('test score : {}'.format(elastic.score(X_test, y_test)))

train score : 0.7506541823292177
test score : 0.6683943813675851


In [ ]:
elastic.coef_, elastic.intercept_

(array([-1.11752838e-01,  3.08045731e-02,  2.94653747e-02,  2.70895909e+00,
        -1.46575791e+01,  4.45107972e+00, -8.27533203e-03, -1.41133421e+00,
         2.57719116e-01, -1.09135123e-02, -8.86315016e-01,  1.24492033e-02,
        -5.13360477e-01]), 28.505089940586423)

3. mse

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
train_mse = mean_squared_error(y_train, y_pred)
train_mse

21.641412753226323

In [ ]:
y_train.std(), y_pred.std()

(9.320590315691252, 8.076632409595662)

4. R2_score

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_train, y_pred)

0.7508856358979672

## Boston extended Dataset

In [ ]:
!pip install mglearn

     |████████████████████████████████| 542kB 2.8MB/s 
  Created wheel for mglearn: filename=mglearn-0.1.9-py2.py3-none-any.whl size=582638 sha256=f1ef3ad2bbdf938b35add4778139d9d29a3e4bf81156a926d9770eae94f837a9
  Stored in directory: /root/.cache/pip/wheels/eb/a6/ea/a6a3716233fa62fc561259b5cb1e28f79e9ff3592c0adac5f0
Successfully built mglearn


In [ ]:
import mglearn

In [ ]:
from mglearn.datasets import load_extended_boston

In [ ]:
boston_extended = load_extended_boston()

In [ ]:
boston_extended

(array([[0.00000000e+00, 1.80000000e-01, 6.78152493e-02, ...,
         1.00000000e+00, 8.96799117e-02, 8.04248656e-03],
        [2.35922539e-04, 0.00000000e+00, 2.42302053e-01, ...,
         1.00000000e+00, 2.04470199e-01, 4.18080621e-02],
        [2.35697744e-04, 0.00000000e+00, 2.42302053e-01, ...,
         9.79579831e-01, 6.28144504e-02, 4.02790570e-03],
        ...,
        [6.11892474e-04, 0.00000000e+00, 4.20454545e-01, ...,
         1.00000000e+00, 1.07891832e-01, 1.16406475e-02],
        [1.16072990e-03, 0.00000000e+00, 4.20454545e-01, ...,
         9.82676920e-01, 1.29930407e-01, 1.71795127e-02],
        [4.61841693e-04, 0.00000000e+00, 4.20454545e-01, ...,
         1.00000000e+00, 1.69701987e-01, 2.87987643e-02]]),
 array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7,

In [ ]:
X_extended, y_extended = boston_extended

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_extended, y_extended, 
                                                    test_size=0.2, random_state=42)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((404, 104), (404,), (102, 104), (102,))

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg = LinearRegression().fit(X_train, y_train)

In [ ]:
print('train score : {}'.format(log_reg.score(X_train, y_train)))
print('test score : {}'.format(log_reg.score(X_test, y_test)))

train score : 0.94093170271135
test score : 0.805582944797218


In [ ]:
log_reg.coef_, log_reg.intercept_

(array([-4.68916921e+02,  1.81755400e+01, -9.82349941e+01,  1.36193364e+01,
         3.25031052e+01,  6.53975165e+01,  3.25560208e+01, -2.84628034e+01,
         9.68934569e+00,  6.48362270e+01,  1.41418899e+01,  3.57858651e+01,
         6.07807386e+00,  3.20435497e+00,  7.01047098e+02,  1.36083249e+03,
         2.29313816e+02, -8.78762975e+01,  8.75779665e+01, -1.86254119e+01,
        -7.27870330e+01,  6.40149331e+02, -1.66202225e+03,  5.45754843e+02,
        -1.48495205e+01,  1.06780706e+02, -4.39361143e+00, -1.33886010e+01,
        -4.13517309e+00, -6.64912882e+01, -1.83940066e+00,  1.20252839e+01,
        -2.32085934e+01, -3.89846515e+01,  4.45581835e+01, -2.95985368e+00,
         3.22510699e+00, -3.60031726e+01,  4.01516752e+01, -7.22997978e-01,
        -2.85144058e+00,  4.78397894e+01,  1.16095836e+01,  4.59136539e+01,
        -2.07990364e+01,  2.98497609e+00, -4.21383649e+00,  3.41186956e+01,
        -1.82464812e+01,  1.36193364e+01, -1.78208749e+01, -2.74868041e+01,
        -3.3

1. Ridge / Lasso / ElasticNet

In [ ]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.1).fit(X_train, y_train)
print('train score : {}'.format(ridge.score(X_train, y_train)))
print('test score : {}'.format(ridge.score(X_test, y_test)))

train score : 0.9120292678182622
test score : 0.8510741726311931


In [ ]:
ridge.coef_, ridge.intercept_

(array([-3.48100826e+00, -5.13295313e+00, -6.06465144e+00,  6.14751415e+00,
         6.93438605e+00,  2.21947921e+01,  4.34688798e+00, -1.20585252e+01,
         1.19333178e+01, -6.13957122e-01, -1.35827525e+00,  1.36542212e+01,
        -2.41584930e+00,  7.03256386e+00,  2.01286746e-02, -1.71624714e+00,
         1.01661058e+01, -1.44372730e+00,  4.86046718e+00, -3.13350380e+00,
        -1.58317155e-01, -4.58541574e+00, -3.54546626e+00, -3.39881916e+00,
        -2.97033288e+00,  2.91180326e+00,  2.64012812e+00, -2.01933860e+00,
         7.12315499e+00,  1.22627046e+00,  6.16733278e+00, -1.87285940e+00,
        -1.26857007e+00, -1.98022697e+00,  9.12224571e+00,  5.82962948e+00,
        -3.16747750e+00, -7.01542085e+00,  6.61394735e+00,  4.12495876e+00,
         7.16590615e+00,  4.32046716e+00,  4.53014915e+00, -4.40257393e+00,
         4.09389310e+00,  8.21851151e+00, -8.58296820e+00,  9.93570316e-01,
        -1.33247206e+01,  6.14751415e+00, -1.46646420e+01, -1.84897413e+01,
         3.4

In [ ]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.1).fit(X_train, y_train)
print('train score : {}'.format(lasso.score(X_train, y_train)))
print('test score : {}'.format(lasso.score(X_test, y_test)))

train score : 0.7469971327325291
test score : 0.6960152938224358


In [ ]:
lasso.coef_, lasso.intercept_

(array([ -0.        ,   0.        ,  -0.        ,   0.        ,
         -0.        ,   0.        ,  -0.        ,  -1.26436813,
         -0.        ,  -0.        ,  -5.47530812,   0.        ,
        -15.44014065,  -0.        ,   0.        ,  -0.        ,
          0.        ,  -0.        ,  -0.        ,  -0.        ,
         -0.        ,  -0.        ,  -0.        ,  -0.        ,
         -0.        ,  -0.        ,   0.        ,  -0.        ,
          0.        ,   0.        ,   0.        ,  -0.        ,
         -0.        ,  -0.        ,  -0.        ,  -0.        ,
          0.        ,  -0.        ,   0.        ,   0.        ,
         -0.        ,  -0.        ,  -0.        ,  -0.        ,
         -0.        ,  -0.        ,  -0.        ,   0.        ,
         -0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   2.28418167,  -0.        ,  -0.67552475,
         -0.        ,  -0.        ,  -0.

In [ ]:
from sklearn.linear_model import ElasticNet
elastic = ElasticNet(alpha=0.1, l1_ratio=0.5).fit(X_train, y_train)
print('train score : {}'.format(elastic.score(X_train, y_train)))
print('test score : {}'.format(elastic.score(X_test, y_test)))

train score : 0.6942023466705182
test score : 0.6478981885404185


In [ ]:
elastic.coef_, elastic.intercept_

(array([-0.18096378,  0.06468358, -0.44527091,  0.62597541, -0.42004792,
         3.7633937 , -0.        , -1.13742281,  0.        , -0.50618089,
        -2.09797145,  0.95165746, -3.82261288, -0.        ,  0.        ,
        -0.        ,  0.        , -0.        , -0.        , -0.09115656,
        -0.        , -0.17384041, -0.07806332, -0.        , -0.        ,
        -0.        ,  0.        , -0.        ,  0.        ,  0.        ,
         0.59126226,  0.        , -0.        ,  0.        , -0.        ,
        -0.        ,  0.08054046, -0.        , -0.        ,  0.        ,
        -0.4568239 , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.30916117, -0.        , -1.24434019,  0.62600078,
        -0.        ,  0.53247732,  0.1865154 ,  0.        ,  0.82761362,
         0.58080713,  0.18801619,  0.85604381, -0.        , -1.10908839,
         0.        , -0.35110434, -0.        , -0.        , -0.37867878,
        -0.76292911,  0.        , -1.38208259,  5.7